versions:
  "1.23":
    test_config:
      cmd:
        - kube-score version
        - kubeval --version
        - kubent
        - kustomize version
        - helm version
        - aws --version
        - helm diff version
    build_args:
      HELM_DIFF_VERSION: 3.1.3
      HELM_VERSION: 3.8.1
      KUBECTL_VERSION: 1.23.4
      KUBENT_VERSION: 0.5.1
      KUBESCORE_VERSION: 1.14.0
      KUBEVAL_VERSION: 0.16.1
      KUSTOMIZATION_VERSION: 4.5.2
